export enum TokenTypes {
  OTHER = 'Other',
  COLOR = 'Color',
  BORDER_RADIUS = 'BorderRadius',
  SIZING = 'Sizing',
  SPACING = 'Spacing',
  TEXT = 'Text',
  TYPOGRAPHY = 'Typography',
  OPACITY = 'Opacity',
  BORDER_WIDTH = 'BorderWidth',
  BOX_SHADOW = 'BoxShadow',
  FONT_FAMILIES = 'FontFamilies',
  FONT_WEIGHTS = 'FontWeights',
  LINE_HEIGHTS = 'LineHeights',
  FONT_SIZES = 'FontSizes',
  LETTER_SPACING = 'LetterSpacing',
  PARAGRAPH_SPACING = 'ParagraphSpacing',
  TEXT_DECORATION = 'TextDecoration',
  TEXT_CASE = 'TextCase',
  COMPOSITION = 'Composition',
}
